# Changes here will be overwritten by Copier
_commit: v0.1.6
_src_path: https://gitlab.softwareheritage.org/swh/devel/swh-py-template.git
description: Software Heritage scheduler
distribution_name: swh-scheduler
have_cli: true
have_workers: false
package_root: swh/scheduler
project_name: swh.scheduler
python_minimal_version: '3.7'
readme_format: rst
