[project]
name = "swh.scheduler"
authors = [
    {name="Software Heritage developers", email="swh-devel@inria.fr"},
]

description = "Software Heritage scheduler"
readme = {file = "README.rst", content-type = "text/x-rst"}
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
]
dynamic = ["version", "dependencies", "optional-dependencies"]

[tool.setuptools.packages.find]
include = ["swh.*"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt", "requirements-swh.txt"]}

[tool.setuptools.dynamic.optional-dependencies]
journal = {file = ["requirements-journal.txt"]}
simulator = {file = ["requirements-simulator.txt"]}
testing = {file = [
    "requirements-test.txt",
    "requirements-journal.txt",
    "requirements-simulator.txt",
    ]}

[project.entry-points."swh.cli.subcommands"]
"swh.scheduler" = "swh.scheduler.cli"
"swh.scheduler.journal" = "swh.scheduler.cli.journal"

[project.urls]
"Homepage" = "https://gitlab.softwareheritage.org/swh/devel/swh-scheduler"
"Bug Reports" = "https://gitlab.softwareheritage.org/swh/devel/swh-scheduler/-/issues"
"Funding" = "https://www.softwareheritage.org/donate"
"Documentation" = "https://docs.softwareheritage.org/devel/swh-scheduler/"
"Source" = "https://gitlab.softwareheritage.org/swh/devel/swh-scheduler.git"

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
fallback_version = "0.0.1"

[tool.black]
target-version = ['py37']

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
force_sort_within_sections = true
known_first_party = ['swh']
